<?php

declare(strict_types=1);

namespace Intervention\Zodiac\Chinese;

use Intervention\Zodiac\Exceptions\InvalidArgumentException;
use Intervention\Zodiac\Interfaces\SignInterface;
use Intervention\Zodiac\Western\Compatibility as WesternCompatibility;

class Compatibility extends WesternCompatibility
{
    /**
     * @throws InvalidArgumentException
     */
    public function __invoke(SignInterface $a, SignInterface $b): float
    {
        if (!($a instanceof ChineseSign) || !($b instanceof ChineseSign)) {
            throw new InvalidArgumentException('The signs being compared must have the same astrology');
        }

        return match ($a) {
            ChineseSign::Rat => match ($b) {
                ChineseSign::Rat => .5,
                ChineseSign::Ox => .8,
                ChineseSign::Tiger => .5,
                ChineseSign::Rabbit => 0,
                ChineseSign::Dragon => 1,
                ChineseSign::Snake => .5,
                ChineseSign::Horse => .3,
                ChineseSign::Goat => .2,
                ChineseSign::Monkey => 1,
                ChineseSign::Rooster => .5,
                ChineseSign::Dog => .5,
                ChineseSign::Pig => .5,
            },
            ChineseSign::Ox => match ($b) {
                ChineseSign::Rat => .8,
                ChineseSign::Ox => .5,
                ChineseSign::Tiger => .5,
                ChineseSign::Rabbit => .5,
                ChineseSign::Dragon => .5,
                ChineseSign::Snake => 1,
                ChineseSign::Horse => .2,
                ChineseSign::Goat => .3,
                ChineseSign::Monkey => .5,
                ChineseSign::Rooster => 1,
                ChineseSign::Dog => .5,
                ChineseSign::Pig => .5,
            },
            ChineseSign::Tiger => match ($b) {
                ChineseSign::Rat => .5,
                ChineseSign::Ox => .5,
                ChineseSign::Tiger => .5,
                ChineseSign::Rabbit => .5,
                ChineseSign::Dragon => .5,
                ChineseSign::Snake => .2,
                ChineseSign::Horse => 1,
                ChineseSign::Goat => .5,
                ChineseSign::Monkey => .3,
                ChineseSign::Rooster => .5,
                ChineseSign::Dog => 1,
                ChineseSign::Pig => .8,
            },
            ChineseSign::Rabbit => match ($b) {
                ChineseSign::Rat => 0,
                ChineseSign::Ox => .5,
                ChineseSign::Tiger => .5,
                ChineseSign::Rabbit => .5,
                ChineseSign::Dragon => .2,
                ChineseSign::Snake => .5,
                ChineseSign::Horse => .5,
                ChineseSign::Goat => 1,
                ChineseSign::Monkey => .5,
                ChineseSign::Rooster => .3,
                ChineseSign::Dog => .8,
                ChineseSign::Pig => 1,
            },
            ChineseSign::Dragon => match ($b) {
                ChineseSign::Rat => 1,
                ChineseSign::Ox => .5,
                ChineseSign::Tiger => .5,
                ChineseSign::Rabbit => .2,
                ChineseSign::Dragon => 0,
                ChineseSign::Snake => .5,
                ChineseSign::Horse => .5,
                ChineseSign::Goat => .5,
                ChineseSign::Monkey => 1,
                ChineseSign::Rooster => .8,
                ChineseSign::Dog => .3,
                ChineseSign::Pig => .5,
            },
            ChineseSign::Snake => match ($b) {
                ChineseSign::Rat => .5,
                ChineseSign::Ox => 1,
                ChineseSign::Tiger => .2,
                ChineseSign::Rabbit => .5,
                ChineseSign::Dragon => .5,
                ChineseSign::Snake => .5,
                ChineseSign::Horse => .5,
                ChineseSign::Goat => .5,
                ChineseSign::Monkey => .8,
                ChineseSign::Rooster => 1,
                ChineseSign::Dog => .5,
                ChineseSign::Pig => .3,
            },
            ChineseSign::Horse => match ($b) {
                ChineseSign::Rat => .3,
                ChineseSign::Ox => .2,
                ChineseSign::Tiger => 1,
                ChineseSign::Rabbit => .5,
                ChineseSign::Dragon => .5,
                ChineseSign::Snake => .5,
                ChineseSign::Horse => 0,
                ChineseSign::Goat => .8,
                ChineseSign::Monkey => .5,
                ChineseSign::Rooster => .5,
                ChineseSign::Dog => 1,
                ChineseSign::Pig => .5,
            },
            ChineseSign::Goat => match ($b) {
                ChineseSign::Rat => .2,
                ChineseSign::Ox => .3,
                ChineseSign::Tiger => .5,
                ChineseSign::Rabbit => 1,
                ChineseSign::Dragon => .5,
                ChineseSign::Snake => .5,
                ChineseSign::Horse => .8,
                ChineseSign::Goat => .5,
                ChineseSign::Monkey => .5,
                ChineseSign::Rooster => .5,
                ChineseSign::Dog => .5,
                ChineseSign::Pig => 1,
            },
            ChineseSign::Monkey => match ($b) {
                ChineseSign::Rat => 1,
                ChineseSign::Ox => .5,
                ChineseSign::Tiger => .3,
                ChineseSign::Rabbit => .5,
                ChineseSign::Dragon => 1,
                ChineseSign::Snake => .8,
                ChineseSign::Horse => .5,
                ChineseSign::Goat => .5,
                ChineseSign::Monkey => .5,
                ChineseSign::Rooster => .5,
                ChineseSign::Dog => .5,
                ChineseSign::Pig => .2,
            },
            ChineseSign::Rooster => match ($b) {
                ChineseSign::Rat => .5,
                ChineseSign::Ox => 1,
                ChineseSign::Tiger => .5,
                ChineseSign::Rabbit => .3,
                ChineseSign::Dragon => .8,
                ChineseSign::Snake => 1,
                ChineseSign::Horse => .5,
                ChineseSign::Goat => .5,
                ChineseSign::Monkey => .5,
                ChineseSign::Rooster => 0,
                ChineseSign::Dog => .2,
                ChineseSign::Pig => .5,
            },
            ChineseSign::Dog => match ($b) {
                ChineseSign::Rat => .5,
                ChineseSign::Ox => .5,
                ChineseSign::Tiger => 1,
                ChineseSign::Rabbit => .8,
                ChineseSign::Dragon => .3,
                ChineseSign::Snake => .5,
                ChineseSign::Horse => 1,
                ChineseSign::Goat => .5,
                ChineseSign::Monkey => .5,
                ChineseSign::Rooster => .2,
                ChineseSign::Dog => .5,
                ChineseSign::Pig => .5,
            },
            ChineseSign::Pig => match ($b) {
                ChineseSign::Rat => .5,
                ChineseSign::Ox => .5,
                ChineseSign::Tiger => .8,
                ChineseSign::Rabbit => 1,
                ChineseSign::Dragon => .5,
                ChineseSign::Snake => .3,
                ChineseSign::Horse => .5,
                ChineseSign::Goat => 1,
                ChineseSign::Monkey => .2,
                ChineseSign::Rooster => .5,
                ChineseSign::Dog => .5,
                ChineseSign::Pig => 0,
            },
        };
    }
}
